CFLAGS=-Wall -c -g -O2 -DXP_UNIX
LDFLAGS=-lmozjs -lcurl
export LDFLAGS CFLAGS

JS_FILE = main.js

JS_FILE_COMPONENTS = \
    js/json2.js \
    js/filter.js \
    js/mimeparse.js \
    js/render.js \
    js/state.js \
    js/util.js \
    js/validate.js \
    js/views.js


JS_FILE_COMPONENTS_LAST = js/loop.js


all:
	./rebar compile

verbose:
	./rebar compile verbose=1

clean:
	./rebar clean

$(JS_FILE): $(JS_FILE_COMPONENTS) $(JS_FILE_COMPONENTS_LAST)
	mkdir -p `dirname $(JS_FILE)`
	echo "// DO NOT EDIT THIS FILE BY HAND" > $@
	echo >> $@
	cat $^ >> $@

js: $(JS_FILE)

jsclean:
	@rm -f main.js
